# Generated by Django 3.2 on 2021-05-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='_shop_product_options_+', to='shop.Product'),
        ),
    ]
