# Generated by Django 3.2 on 2021-05-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shop_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='weekDay',
            new_name='offDays',
        ),
    ]
